version: "3.8"

services:
  kuma:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    networks:
      - npm-network
    volumes:
      - /srv/uptime-kuma:/app/data
    container_name: "uptime-kuma"

networks:
  npm-network:
    external: true